### ISSUE TITLE
Tried updating some tests

### ISSUE THREAD

**Issue by phated** [iceddev/daoist-model#1]
@briancavalier I tried updating some tests in https://github.com/iceddev/daoist-model/tree/tests to be CommonJS friendly.  Ran into some problems around `Object.create` and `Property` instances so I dumped dojo's delegate implementation in `Model`.  Is this how you envision usage of the non-`dojo/declare` version?  I was a bit confused (to say the least)

**Comment by briancavalier** [comment]
I don't claim that any of it works currently :)

> Is this how you envision usage of the non-dojo/declare version?

Is _what_ how I envision it?  :)  What did you try?

My goal is that Model should work as plain JavaScript, without the need for `dojo/declare` etc.  For example, the following worked in node for me just now:

``` txt
> node
>  var Model = require('./Model');
undefined
> var MyModel = function() { Model.apply(this, arguments); }
undefined
> MyModel.prototype = Object.create(Model.prototype);
{}
> var mm = new MyModel();
undefined
> mm
{ schema: {}, additionalProperties: true, _scenario: 'insert' }
```

ie inheriting from Model and creating an instance using `new`.  Creating a Model instance directly with `new` works, as does creating a `Property` instance (`Property` just inherits from `Model` anyway):

``` txt
> var Model = require('./Model');
undefined
> var p = new Model.Property();
undefined
> p
{ schema: {},
  additionalProperties: true,
  _scenario: 'update',
  validateOnSet: true,
  validators: null }
```

This is, of course, just the basics.  IOW, making the code work _at all_ in commonjs and without `dojo/declare` is step 1 :)

Does that help?  Did you have something entirely different in mind?

**Comment by phated** [comment]
Sorry, here's what I did in the tests:

``` js
var util = require('util');

function TestModel(options){
    this.schema = {
        string: 'string',
        number: 'number',
        boolean: 'boolean',
        object: Object,
        array: Array,
        any: {},
        accessor: {
            put: function (value) {
                return this._parent._accessor = value;
            },
            valueOf: function () {
                return this._parent._accessor;
            }
        }
    };

    this.additionalProperties = false;

    Model.call(this, options);
}
util.inherits(TestModel, Model);

var model = new TestModel();
```

This required a change to `Model` at https://github.com/iceddev/daoist-model/blob/tests/Model.js#L134-L135

**Comment by phated** [comment]
It seems a little strange to define the schema like that though.

**Comment by briancavalier** [comment]
Ah, ok.  I'll move `schema` back to a prototype property.  I tend to be wary of prototype properties, but in this case it makes sense for `schema` to be per type, rather than per instance.

**Comment by briancavalier** [comment]
Just pushed an update that moves properties that are declared as prototype props in the original fork back to the prototypes in the wip-port-commonjs branch.

[Here's a gist](https://gist.github.com/briancavalier/483e5e6602959a13c551) showing that schema and additionalProperties can be defined per type now.

**Comment by phated** [comment]
Interesting.  Looks a bit better than my example

**Comment by briancavalier** [comment]
I think there's really only two options: per instance, or per type, no matter the particular way in which that's implemented.  Per type actually gives you both, since you could still set `concreateModelInstance.schema = someOtherSchema;`, or doing it in the constructor as you did would work too.  So yeah, this feels right.

Should we close this?

**Comment by phated** [comment]
Yeah,  I think this is fine to close.  I am fine with the idea of it on the prototype.  We might also expose a function for quickly setting the prototype and getting a constructor, similar to backbone.Model

**Comment by briancavalier** [comment]
> I am fine with the idea of it on the prototype

Cool.  It deviates as little as possible from the way the original version worked, which also put the property on the prototype.

> We might also expose a function for quickly setting the prototype and getting a constructor

Sure, that'd be easy enough, and probably convenient since we probably don't want to assume devs will use `require('utils').inherit`.
